### ISSUE TITLE
very poor result

### ISSUE THREAD

**Issue by scut-xz** [17231087/DPVP#2]
I download the MT-small dataset from the source, and run the code, but I got a very poor result that different from the paper.
I have not modified any parameters in the config file. What modifications do I need to make to get the same results as in the paper?
I would be very grateful if I could receive your reply.
![result](https://github.com/17231087/DPVP/assets/59855379/ec518a7c-a4bc-4b99-92c2-5705fb4caff4)

**Comment by zhangyuting725** [comment]
<img width="803" alt="image" src="https://github.com/17231087/DPVP/assets/47213017/f29eb82a-271b-45e8-aa7f-15762218a6bf">
Read only 100 lines of data for a simple test and forget to modify it. I'm sorry for my mistake. You can comment on the size limit of the read data in utils.py (nrows= 100).

**Comment by scut-xz** [comment]
Problem solved, thank you for your reply！
